name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Cache install nix packages
      uses: mtoohey31/cache-flake-attrs@v2
      id: nix-cache
      with:
        key: ${{ runner.os }}-nix-store-${{ hashFiles('flake.lock', 'flake.nix') }}

    - uses: HatsuneMiku3939/direnv-action@v1

    - run: playwright pdf google.com a.pdf
