name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Cache Nix store
      uses: actions/cache@v3.0.8
      id: nix-cache
      with:
        path: /tmp/nixcache
        key: ${{ runner.os }}-nix-store-${{ hashFiles("flake.lock") }}

    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Import Nix store cache
      if: steps.nix-cache.outputs.cache-hit == 'true'
      run: nix-store --import < /tmp/nixcache

    - uses: cachix/cachix-action@v12
      with:
        name: aabccd021nixgithubactionstest
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community

    - run: nix-env -f '<nixpkgs>' -iA direnv

    - run: nix-env -f '<nixpkgs>' -iA nix-direnv

    - uses: aabccd021/direnv-action@v1.0.5

    - run: playwright pdf google.com a.pdf

    - name: Export Nix store cache
      if: steps.nix-cache.outputs.cache-hit != 'true'
      run: nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nixcache
