name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Setup Firebase Emulators cache
      uses: actions/cache@v3
      with:
        path: /nix/store
        key: ${{ runner.os }}-nix-store-${{ hashFiles('flake.lock') }}

    - uses: cachix/install-nix-action@v18

    - run: nix develop

    - run: playwright
