name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Setup Firebase Emulators cache
      uses: actions/cache@v3
      with:
        path: /nix/store
        key: ${{ runner.os }}-nix-store-${{ hashFiles('flake.lock') }}-${{ hashFiles('.github/workflows/build.yml') }}

    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - run: ls /nix/store

    - run: nix-env -f '<nixpkgs>' -iA direnv

    - run: ls /nix/store

    - run: nix develop

    - run: playwright
