name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Setup Nix Store Cache
      uses: actions/cache@v3
      with:
        path: ~/aabccd021
        key: ${{ runner.os }}-nix-store-v2-${{ hashFiles('flake.lock') }}

    - name: Fix Nix Store Permission
      shell: bash
      run: |
        sudo mkdir --parents /nix/store
        sudo mkdir --parents ~/aabccd021
        sudo cp --recursive ~/aabccd021 /nix/store

    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - run: nix-env --store file://$HOME/aabccd021 --file '<nixpkgs>' -iA direnv

    - run: nix-env --store file://$HOME/aabccd021 --file '<nixpkgs>' -iA nix-direnv

    - uses: HatsuneMiku3939/direnv-action@v1

    - run: playwright pdf google.com a.pdf

    - name: Fix Nix Store Permission Cleanup
      shell: bash
      run: |
        sudo rm -rf ~/aabccd021
        sudo mkdir ~/aabccd021
        sudo cp --recursive /nix/store ~/aabccd021


