name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Cache Nix store
      uses: actions/cache@v3
      id: nix-cache
      with:
        path: /tmp/nixcache
        key: ${{ runner.os }}-nix-store-${{ hashFiles('flake.lock') }}

    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Import Nix store cache
      if: steps.nix-cache.outputs.cache-hit == 'true'
      run: nix-store --import < /tmp/nixcache

    - uses: HatsuneMiku3939/direnv-action@v1

    - run: playwright pdf google.com a.pdf

    - name: Export Nix store cache
      if: steps.nix-cache.outputs.cache-hit != 'true'
      run: nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nixcache
