name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Cache install Nix packages
      uses: rikhuijzer/cache-install@v1.0.9
      with:
        key: nix-${{ hashFiles('mypackages.nix') }}
        nix_file: 'flake.nix'

    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - run: nix-env -f '<nixpkgs>' -iA direnv

    - run: nix-env -f '<nixpkgs>' -iA nix-direnv

    - uses: aabccd021/direnv-action@v1.0.5

    - run: playwright pdf google.com a.pdf
