name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: cachix/cachix-action@v12
      with:
        name: aabccd021nixgithubactionstest
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        pathsToPush: dev-profile

    - run: nix develop --profile dev-profile
